//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.04 at 08:09:24 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/crud/person", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.crud.jaxb;
